version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: car_workshop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_workshop
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: car_workshop_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

  app:
    build: .
    container_name: car_workshop_app
    volumes:
      - ./app:/var/www/html
    ports:
      - "8000:80"

volumes:
  db_data:
